FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    jq \
    curl \
    zip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
RUN python3 -m venv /app/venv

ENV PATH="/app/venv/bin:$PATH"
ENV PYTHONUNBUFFERED=1

RUN pip install fastapi uvicorn pandas kubernetes

COPY src/api/kubesnap.py /app/kubesnap.py

COPY src/core/kubesnap_functions.py /app/kubesnap_functions.py

CMD ["python3","kubesnap.py"]